name: Android CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    name: Run tests and upload reports
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew app:testDebugUnitTest

      - name: Run Android Instrumented Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: default
          arch: x86_64
          script: ./gradlew app:connectedDebugAndroidTest

      - name: Generate JaCoCo Code Coverage Report
        run: ./gradlew app:createDebugCoverageReport # Assumed task

      - name: Upload Unit Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-report
          path: app/build/reports/tests/testDebugUnitTest/html/

      - name: Upload Android Instrumented Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: android-instrumented-test-report
          path: app/build/reports/androidTests/connected/

      - name: Upload JaCoCo Code Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-code-coverage-report
          path: app/build/reports/coverage/debug/ # Assumed path
